launch_command: loadpage popular ;; flush ;; history clear
video:
- Play video: run ${video-player} '${embed-url}'
- Play audio: run ${terminal-emulator} ${video-player} '${embed-url}' --no-video
- Play audio (loop): run ${terminal-emulator} ${video-player} '${embed-url}' --no-video --loop-file=inf
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Download video (webm): run ${terminal-emulator} ${youtube-downloader} -o ${download-path} '${embed-url}'
- Download audio (opus): run ${terminal-emulator} ${youtube-downloader} -o ${download-path} '${embed-url}' -x
- 'Mode: ${provider}': switchprovider
playlist:
- Switch view: '%switch-view%'
- Play all videos: run ${video-player} ${all-videos}
- Play all audio: run ${terminal-emulator} ${video-player} ${all-videos} --no-video
- Shuffle play all audio: run ${terminal-emulator} ${video-player} ${all-videos} --no-video --shuffle
- Shuffle play all audio (loop): run ${terminal-emulator} ${video-player} ${all-videos} --no-video --shuffle --loop-playlist=inf
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Download all video (webm): run ${terminal-emulator} ${youtube-downloader} -o ${download-path} ${all-videos}
- Download all audio (opus): run ${terminal-emulator} ${youtube-downloader} -o ${download-path} ${all-videos} -x
- 'Mode: ${provider}': switchprovider
