global:
  'f':
    2: run ${browser} '${url}'
  'c':
    2: cp ${url}
search:
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
  'p':
    2: run mpv '${hover-url}'
popular:
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
  'p':
    2: run mpv '${hover-url}'
trending:
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'p':
    2: run mpv '${hover-url}'
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
video: {}
playlist:
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
  'p':
    2: run mpv '${hover-url}'
channel_main: {}
channel_videos:
  'p':
    2: run mpv '${hover-url}'
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
channel_playlists:
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
  'p':
    2: run mpv '${hover-url}'
watchhistory:
  'p':
    2: run mpv '${hover-url}'
  'A':
    1: run ${terminal-emulator} mpv '${hover-url}' --no-video --loop-playlist=inf --shuffle
  'a':
    2: run ${terminal-emulator} mpv '${hover-url}' --no-video
